# Generated by Django 3.2.4 on 2021-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimesSeqNum',
            fields=[
                ('trip_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(max_length=45)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_type', models.TextField(blank=True, null=True)),
                ('drop_off_type', models.TextField(blank=True, null=True)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
                ('route_id', models.CharField(blank=True, max_length=45, null=True)),
                ('route_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'stop_times_seq_num',
                'managed': False,
            },
        ),
    ]
