# Generated by Django 3.2.4 on 2021-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stoptimesseqnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='MondayStops',
            fields=[
                ('trip_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(max_length=45)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_type', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_off_type', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'monday_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaturdayStops',
            fields=[
                ('trip_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(max_length=45)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_type', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_off_type', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'saturday_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SundayStops',
            fields=[
                ('trip_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(max_length=45)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_type', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_off_type', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sunday_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TuesdayStops',
            fields=[
                ('trip_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(max_length=45)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_type', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_off_type', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tuesday_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WethfrStops',
            fields=[
                ('trip_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(max_length=45)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_type', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_off_type', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'weThFr_stops',
                'managed': False,
            },
        ),
    ]
